--- #YAML:1.0
name:                IPC-Exe
version:             1.003
abstract:            Execute processes or Perl subroutines & string them via IPC. Think shell pipes.
license:             ~
author:              
    - Gerald Lai
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Spec:                    0
    POSIX:                         0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
